// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBweNq2yIteR3HaPvvtVi62ZmlfcFBcGc',
    appId: '1:659947116204:web:e70d982bbf961232a73109',
    messagingSenderId: '659947116204',
    projectId: 'login-9ff6c',
    authDomain: 'login-9ff6c.firebaseapp.com',
    storageBucket: 'login-9ff6c.appspot.com',
    measurementId: 'G-MC8XB64WY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8J2eg4GHUYV9vnbLPlgbXRgOufoxgtX8',
    appId: '1:659947116204:android:2f29cc7fe374df3ea73109',
    messagingSenderId: '659947116204',
    projectId: 'login-9ff6c',
    storageBucket: 'login-9ff6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4s6RwzifMO6mH80VLKfHtt16uKJ7JDyw',
    appId: '1:659947116204:ios:49135f653fe5a4cca73109',
    messagingSenderId: '659947116204',
    projectId: 'login-9ff6c',
    storageBucket: 'login-9ff6c.appspot.com',
    iosClientId: '659947116204-2shj4r6upvlfstoaavg8sn642ag3ipse.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4s6RwzifMO6mH80VLKfHtt16uKJ7JDyw',
    appId: '1:659947116204:ios:49135f653fe5a4cca73109',
    messagingSenderId: '659947116204',
    projectId: 'login-9ff6c',
    storageBucket: 'login-9ff6c.appspot.com',
    iosClientId: '659947116204-2shj4r6upvlfstoaavg8sn642ag3ipse.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
